/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminMigrateRouteImport } from './routes/admin.migrate'
import { Route as ApiExerciseImageSlugRouteImport } from './routes/api/exercise-image/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrateRoute = AdminMigrateRouteImport.update({
  id: '/admin/migrate',
  path: '/admin/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExerciseImageSlugRoute = ApiExerciseImageSlugRouteImport.update({
  id: '/api/exercise-image/$slug',
  path: '/api/exercise-image/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/finance': typeof FinanceRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/weekly': typeof WeeklyRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/exercise-image/$slug': typeof ApiExerciseImageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/finance': typeof FinanceRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/weekly': typeof WeeklyRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/exercise-image/$slug': typeof ApiExerciseImageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/finance': typeof FinanceRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/weekly': typeof WeeklyRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/exercise-image/$slug': typeof ApiExerciseImageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/finance'
    | '/kanban'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/weekly'
    | '/workouts'
    | '/admin/migrate'
    | '/api/auth/$'
    | '/api/exercise-image/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/finance'
    | '/kanban'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/weekly'
    | '/workouts'
    | '/admin/migrate'
    | '/api/auth/$'
    | '/api/exercise-image/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/finance'
    | '/kanban'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/weekly'
    | '/workouts'
    | '/admin/migrate'
    | '/api/auth/$'
    | '/api/exercise-image/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FinanceRoute: typeof FinanceRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  ProfileRoute: typeof ProfileRoute
  WeeklyRoute: typeof WeeklyRoute
  WorkoutsRoute: typeof WorkoutsRoute
  AdminMigrateRoute: typeof AdminMigrateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExerciseImageSlugRoute: typeof ApiExerciseImageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migrate': {
      id: '/admin/migrate'
      path: '/admin/migrate'
      fullPath: '/admin/migrate'
      preLoaderRoute: typeof AdminMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exercise-image/$slug': {
      id: '/api/exercise-image/$slug'
      path: '/api/exercise-image/$slug'
      fullPath: '/api/exercise-image/$slug'
      preLoaderRoute: typeof ApiExerciseImageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  FinanceRoute: FinanceRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  ProfileRoute: ProfileRoute,
  WeeklyRoute: WeeklyRoute,
  WorkoutsRoute: WorkoutsRoute,
  AdminMigrateRoute: AdminMigrateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExerciseImageSlugRoute: ApiExerciseImageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
